name: fetch-benchmark-results

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-benchmark-results:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts from Salsita repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SALSITA_REPO: "bjogart/salsita"
          DEST_DIR: "raw"
        run: |
          set -euxo pipefail
          mkdir --parents "$DEST_DIR"
          echo "Fetch list of artifacts from $SALSITA_REPO"
          API_URL="https://api.github.com/repos/$SALSITA_REPO/actions/artifacts"
          ARTIFACTS_JSON=$(curl --silent --header "Authorization: token $GITHUB_TOKEN" "$API_URL")
          jq --raw-output '.artifacts[] | select(.name | test("^bench--")) | "\(.name)\t\(.archive_download_url)"' <<< "$ARTIFACTS_JSON" |
          while IFS=$'\t' read -r name url; do
            DEST_FILE="$DEST_DIR/${name}.json"
            if [ -f "$DEST_FILE" ]; then
              continue
            fi
            echo "Download $url"
            DEST_ARC="$DEST_DIR/${name}.zip"
            curl --location --header "Authorization: token $GITHUB_TOKEN" --output "$DEST_ARC" "$url"
            unzip "$DEST_ARC" -d "$DEST_DIR"
            rm "$DEST_ARC"
          done
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain "$DEST_DIR")" ]; then
            git pull
            date=$(date '+%F')
            branch="$date/bench-data"
            git checkout -B $branch
            git add "$DEST_DIR"
            git commit -m "Add benchmark data up to $date"
            git push --set-upstream origin $branch
            gh pr create --fill
          else
            echo "No new benchmark files to commit"
          fi
