name: fetch-benchmark-results

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  fetch-benchmark-results:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install --yes jq

      - name: Download artifacts from Salsita repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SALSITA_REPO: "bjogart/salsita"
          DEST_DIR: "raw"
        run: |
          set -euxo pipefail
          mkdir --parents $DEST_DIR
          echo "Fetch list of artifacts from $SALSITA_REPO"
          API_URL="https://api.github.com/repos/$SALSITA_REPO/actions/artifacts"
          ARTIFACTS_JSON=$(curl --silent --header "Authorization: token $GITHUB_TOKEN" "$API_URL")
          ARTIFACT_URLS=$(echo "$ARTIFACTS_JSON" | jq --raw-output '.artifacts[] | select(.name | test("^bench--")) | .archive_download_url')
          for url in $ARTIFACT_URLS; do
            ARTIFACT_NAME=$(basename "$url")
            DEST_FILE="$DEST_DIR/$ARTIFACT_NAME.json"
            if [ -f "$DEST_FILE" ]; then
              continue
            fi
            echo "Download $url"
            DEST_ARC="$DEST_DIR/$ARTIFACT_NAME.zip"
            curl --location --header "Authorization: token $GITHUB_TOKEN" --output "$DEST_ARC" "$url"
            gzip --decompress "$DEST_ARC" > "$DEST_FILE"
            rm "$DEST_ARC"
          done
      - name: Commit new benchmark results
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain "$DEST_DIR")" ]; then
            git add "$DEST_DIR"
            git commit -m "Add new benchmark results"
            git push
          else
            echo "No new benchmark files to commit."
          fi